recommit : setting connection between staging and production

diff --git a/.github/workflows/create-pr-to-prod.yml b/.github/workflows/create-pr-to-prod.yml
--- a/.github/workflows/create-pr-to-prod.yml
+++ b/.github/workflows/create-pr-to-prod.yml
@@ -33,6 +33,8 @@ jobs:
           git clone \
             https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/sakagawa0401/self-introduction.git \
             prod-repo
+            rm -rf prod-repo/.git
+
       - name: Verify cloned repository
         run: |
           ls -la prod-repo
@@ -46,15 +48,12 @@ jobs:
       - name: Commit changes
         run: |
           cd prod-repo
-          # 新規ブランチを切る(適宜わかりやすい命名をする)
           export BRANCH_NAME="staging-sync-$(date +'%Y%m%d%H%M%S')"
+          echo "Branch name: $BRANCH_NAME"
           git checkout -b $BRANCH_NAME
-
           git add .
           git commit -m "Sync from staging $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
-
-          # push
-          git push origin $BRANCH_NAME
+          git push origin $BRANCH_NAME || { echo "Push failed"; exit 1; }
 
       - name: Create Pull Request to production repo
         uses: peter-evans/create-pull-request@v7
